<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="测试模块"
           tests="4"
           failures="2"
           errors="0"
           skipped="0"
           time="0.031">
  <properties />
            <testcase name="logDemo" time="0.015" classname="com.uim.autoapi.test.TestNG">
                <failure type="java.lang.RuntimeException"
                  message="超时啦，超时啦！！！"
              >
<![CDATA[java.lang.RuntimeException: 超时啦，超时啦！！！
  com.uim.autoapi.test.TestNG.logDemo(TestNG.java:23)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
            <testcase name="testCase2" time="0.016" classname="com.uim.autoapi.test.TestNG">
                <failure type="java.lang.AssertionError"
                  message="expected [2] but found [1]"
              >
<![CDATA[java.lang.AssertionError: expected [2] but found [1]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:389)
  org.testng.Assert.assertEquals(Assert.java:399)
  com.uim.autoapi.test.TestNG.testCase2(TestNG.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testCase1" time="0.000" classname="com.uim.autoapi.test.TestNG" />
                <testcase name="testCase3" time="0.000" classname="com.uim.autoapi.test.TestNG" />
      
</testsuite>
